name: Alert Service
language: python
variables:
  - name: alert_topic
    inputType: OutputTopic
    description: Alerts topic
    defaultValue: json-alerts
    required: true
  - name: forecast_data
    inputType: InputTopic
    description: Forecast Data
    defaultValue: forecast
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
