name: InfluxDB 3.0 Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    required: true
  - name: INFLUXDB_HOST
    inputType: Secret
    description: Host address for the InfluxDB instance.
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: Authentication token to access InfluxDB.
    required: true
  - name: INFLUXDB_ORG
    inputType: Secret
    description: Organization name in InfluxDB.
    required: true
  - name: INFLUXDB_DATABASE
    inputType: Secret
    description: Database name in InfluxDB where data should be stored.
    required: true
  - name: INFLUXDB_TAG_KEYS
    inputType: FreeText
    description: Columns to be used as tags when writing data to InfluxDB.
    defaultValue: ''
    required: true
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: The InfluxDB measurement to write data to. If not specified, the name of the input topic will be used
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
